language: julia
os:
- linux
julia:
- 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
  - shards
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_SHARDS_DIR=shards
  - BINARYBUILDER_AUTOMATIC_APPLE=true
  - BINARYBUILDER_USE_CCACHE=true
sudo: required
before_script:
- julia -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder#master"; Pkg.build()'
script:
- julia build_tarballs.jl
deploy:
  provider: releases
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: ianshmean/LibAOMBuilder
  api-key:
    secure: SK6sJDOIuCovPhnhZ+xqNfRjrjKkCrMHyHaMxuAiu0gOWbkrpIa7O9SqupElcs1JS/PRDuFlXsoeR+LYxd0kJy6Zo16Ac3CrqD+GNptni63Ig1eUa06/WVullg+gxh8nAL5pwPjvVSuvKRDf18D0O0/tjSB+XaseBNYzI9yJFyGLo524M29vpdfqGaLf/rNLBEEhfTwgpvuCQPsP16lWk0NhNtuWqrBsHtVm8FcsXaUjiVIMlP+v8DeJuXCCGktvuNfHvSKrMqM9V3F6XttvsWek5OgWAsQWl7qyxIAXMJdO7et7ZJYlkw2RaZKOngCkBL42DZ+M3DCmlBPXS0C3FcJ8vH9Kveiz5S36/pe8xwXwbYtQcHWMv4XrfrGIxaAMxR4ilA/eIHAvAORsU3iSCHpSbPCtkR2dwiMRMU9XIauZLXWtbSEVaxcNFH1wxZhD+YJr8Oqw66P8eMl1PuJb7NhICIK3WxCZDSXjGFo7mxJiQUYojDf4WSTuIgYJqHp/3l8POrFp1fZ0nb19m0jvR3etReLGEUF1PgHCbtEybQQawQ8EgspBamDsvW32wIIkuzPqJhdSbhr8s/aauyGuAN57d/T0lRFeBUmmtLJv90DlEM3f8c9hjK4rsIXkAFx2X66L0fUNigFBWeVo2L2iy2yN1qR+9+P8Kgk0TFw8rRo=
